name: Shared PHP test

on:
  workflow_call:
    inputs:
      php-version:
        description: PHP version to test.
        required: true
        type: string

permissions:
  contents: read

jobs:
  test:
    name: PHP ${{ inputs.php-version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php-version }}
          extensions: curl
          coverage: none
      - run: composer validate --strict
      - run: composer update --prefer-dist --no-interaction
      - run: composer lint
      - run: composer test
